src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Family__c</fullName>
        <label>Family</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Family_of_technique</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Image__c</fullName>
        <label>Image</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Type_of_technique</valueSetName>
        </valueSet>
    </fields>
    <label>Product_c</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProductController.cls
public with sharing class ProductController {
    @AuraEnabled
    public static Id createProduct(String productName, String productDescription, Decimal productPrice, String productFamily, String productType, String productImageUrl) {
        Product__c newProduct = new Product__c();
        newProduct.Name = productName;
        newProduct.Description__c = productDescription;
        newProduct.Family__c = productFamily;
        newProduct.Type__c = productType;
        newProduct.Price__c = productPrice;
        if (productImageUrl != null && productImageUrl != '') {
            newProduct.Image__c = productImageUrl;
        } else {
            Http http = new Http();
            HttpRequest request = new HttpRequest();
            request.setEndpoint('http://www.glyffix.com/api/Image?word=' + EncodingUtil.urlEncode(productName, 'UTF-8'));
            request.setMethod('GET');
            HttpResponse response = http.send(request);
            if (response.getStatusCode() == 200) {
                Map<String, Object> results = (Map<String, Object>) JSON.deserializeUntyped(response.getBody());
                newProduct.Image__c = (String) results.get('image_url');
            }
        }
        insert newProduct;
        return newProduct.Id;
    }
}