src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Family__c</fullName>
        <label>Family</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Family_of_technique</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Type_of_technique</valueSetName>
        </valueSet>
    </fields>
    <label>Product_c</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProductSearchController.cls
public with sharing class ProductSearchController {
    @AuraEnabled
    public static List<Product__c> searchProducts(String name, String description) {
        String nameFilter = '%' + name + '%';
        List<Product__c> products = [SELECT Id, Name, Description__c, Family__c, Type__c FROM Product__c WHERE Name LIKE :nameFilter];
        if (!String.isEmpty(description)) {
            products = products.stream().filter(product - > product.Description__c.includes(description)).collect(Collectors.toList());
        }
        return products;
    }
}